name: SimplePolice
author: ramdon_person
main: com.voidcitymc.www.Main
version: 2.0
api-version: 1.15
depend: [Essentials, WorldGuard, WorldEdit]
commands:
   police:
      description: Your description
      usage: /police

permissions:
  police.add:
    description: Allows you to add a police
    default: false
  police.remove:
    description: Allows you to remove a police
    default: false
