name: SimplePolice
author: ramdon_person
main: com.voidcitymc.www.Main
version: 2.0
depend: [Essentials, WorldGuard, WorldEdit]
commands:
   police:
      description: Your description
      usage: /police

permissions:
  police.add:
    description: Allows you to add a police
    default: false
  police.remove:
    description: Allows you to remove a police
    default: false
  police.help:
    description: Allows you to see the help pages
    default: false
  police.list:
    description: Allows you to see the list of police
    default: false
  police.unjail:
    description: Allows you to unjail someone
    default: false
